### ISSUE TITLE
Nightly publish job failing

### ISSUE THREAD

**Issue by bwertman-rc** [intoli/user-agents#65] opened 2023-09-27 17:25 UTC
The nightly build to update the user-agent json has been failing for about two months.
https://app.circleci.com/pipelines/github/intoli/user-agents?branch=master

**Comment by sudiphed** [comment] 2023-10-10 15:39
This might correspond to the migration from Google Universal Analytics to Google Analytics 4: https://support.google.com/analytics/answer/11583528?hl=en

**Comment by xpose2000** [comment] 2023-10-13 01:08
> This might correspond to the migration from Google Universal Analytics to Google Analytics 4: https://support.google.com/analytics/answer/11583528?hl=en

I reached out to the author and you are correct. They need a new data source because GA4 does not have all of the metadata required to generate user agents.

So unless a new data source is found no new builds can be created.

**Comment by xpose2000** [comment] 2023-10-24 01:09
Good news, builds should be working again within 7 days. Fingers crossed.

**Comment by sangaline** [comment] 2023-10-24 13:44
Yes, nightly builds should be working again as of last night! I bumped the minor version to v1.1 because the analytics backend has changed, but everything should be exactly compatible with the earlier versions. Please let me know if you run into any issues with it.

The comments above about Google sunsetting Universal Analytics is correct. The new releases are powered by a new custom analytics backend that was designed to be less reliant on third parties and to facilitate the donation of data from other websites. There will be some updates in the near future that explain more about this.

**Comment by sangaline** [comment] 2023-10-26 20:28
I'm going to close this for now, please create a new issue if you run into any problems with the new releases.

**Closed** 2023-10-26 20:54 UTC
